server: 
  port: 8081

spring: 
  profiles:
    include:
      - aws
  datasource: 
    url: jdbc:log4jdbc:mysql://localhost:3306/odod?useUnicode=true&characterEncoding=utf8&useSSL=false
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    username: admin
    password: admin
  jpa: 
    database: mysql
    generate-ddl: true
    show-sql: true
  thymeleaf: 
    cache: false
    mode: HTML
    prefix: classpath:/
    suffix: .html
    view-names: thymeleaf/*
  es: 
    url: localhost:9200
    username: admin
    password: adminadmin

jwt: 
  secret: jwtsecret

logging: 
  config: classpath:logback-local.xml
